title: "My Portfolio"
theme: jekyll-theme-cayman

# Markdown processor and syntax highlighter
markdown: kramdown
highlighter: rouge

# Base URL (use this only if the site is hosted in a subdirectory)
# Uncomment and set if applicable
# baseurl: "/my-portfolio-site"

# Plugins for additional functionality
plugins:
  - jekyll-feed

# Optional: Enable syntax highlighting for GitHub Pages
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true # Adds line numbers to code blocks
